CREATE TABLE IF NOT EXISTS Persons
(
PersonID int,
LastName varchar(255),
FirstName varchar(255),
Address varchar(255),
City varchar(255)
);

CREATE TABLE USER(
  ID INT NOT NULL PRIMARY KEY,
  FIRST_NAME VARCHAR2 (30) NOT NULL ,
  LAST_NAME VARCHAR2 (30) NOT NULL ,
  USERNAME VARCHAR2 (30) NOT NULL,
  PASSWORD VARCHAR2 (30) NOT NULL,
  TYPE NUMBER (1,0) NOT NULL,
  FK_EVENTS_CREATED INT,
  FK_EVENTS_JOINED INT
);