DROP TABLE USER;
DROP TABLE CONFERENCE_ROOM;
DROP TABLE LOCATION;
DROP TABLE FEATURES;
DROP TABLE EVENT;
DROP TABLE ROOM_OCCUPANCY;

CREATE TABLE IF NOT EXISTS USER(
  FIRST_NAME VARCHAR2 (30) NOT NULL,
  LAST_NAME VARCHAR2 (30) NOT NULL,
  USERNAME VARCHAR2 (30) NOT NULL,
  PASSWORD VARCHAR2 (30) NOT NULL,
  TYPE NUMBER (1,0) NOT NULL,
  FK_EVENTS_CREATED INT,
  FK_EVENTS_JOINED INT
);

CREATE TABLE IF NOT EXISTS CONFERENCE_ROOM(
  ID INT NOT NULL PRIMARY KEY,
  NAME VARCHAR2 (30) NOT NULL,
  PLACES_NUMBER NUMBER (5,0),
  FK_LOCATION INT NOT NULL,
  FK_FEATURES INT NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATION(
  ID INT NOT NULL PRIMARY KEY,
  CITY VARCHAR2 (30) NOT NULL,
  ADDRESS VARCHAR2 (200) NOT NULL,
  BUILDING VARCHAR2 (30) NOT NULL,
  FLOOR VARCHAR2 (5),
  INDICATIONS VARCHAR2 (200)
);

ALTER TABLE CONFERENCE_ROOM
ADD FOREIGN KEY (FK_LOCATION)
REFERENCES LOCATION(ID);

CREATE TABLE IF NOT EXISTS FEATURES(
  ID INT NOT NULL PRIMARY KEY,
  VIDEO_PROJECTOR CHAR (1),
  PROJECTION_SCREEN CHAR (1),
  FLIPCHART CHAR (1),
  WHITEBOARD CHAR (1),
  VIDEO_PLAYER CHAR (1),
  PRINTER CHAR (1),
  LAPTOP CHAR (1),
  SOUND_SYSTEM CHAR (1),
  MICROPHONE CHAR (1),
  WIFI CHAR (1),
  FOTO_VIDEO_SYSTEM CHAR (1),
  CLIMATE_SYSTEM CHAR (1),
  TRANSLATOR CHAR (1)
);

ALTER TABLE CONFERENCE_ROOM
ADD FOREIGN KEY(FK_FEATURES)
REFERENCES FEATURES(ID);

CREATE TABLE IF NOT EXISTS EVENT(
  ID INT NOT NULL PRIMARY KEY,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  START_HOUR TIMESTAMP NOT NULL,
  DURATION NUMBER (2,0) NOT NULL,
  NUMBER_OF_PERSONS NUMBER (5,0) NOT NULL,
  FK_CONFERENCE_ROOM INT NOT NULL
);

ALTER TABLE EVENT
ADD FOREIGN KEY(FK_CONFERENCE_ROOM)
REFERENCES CONFERENCE_ROOM(ID);

CREATE TABLE IF NOT EXISTS ROOM_OCCUPANCY (
  ID INT NOT NULL PRIMARY KEY,
  FK_CONFERENCE_ROOM INT NOT NULL,
  FK_EVENT INT NOT NULL,
  START_HOUR TIMESTAMP NOT NULL,
  END_HOUR TIMESTAMP NOT NULL
);

ALTER TABLE ROOM_OCCUPANCY
ADD FOREIGN KEY (FK_CONFERENCE_ROOM)
REFERENCES CONFERENCE_ROOM(ID);

ALTER TABLE ROOM_OCCUPANCY
ADD FOREIGN KEY (FK_EVENT)
REFERENCES EVENT(ID);
